#!/bin/bash
# chkconfig: - 85 15
# descrīption: service(/usr/bin/flanneld --etcd-endpoints=http://172.20.10.221:4001)

. /etc/rc.d/init.d/functions

start() {
  echo -n $"Starting $prog"
  echo -e " flanneld ：															  [确定]"
  /usr/bin/flanneld --etcd-endpoints=http://172.20.10.221:4001 &
  sleep 1
  echo -e "running..."
}

stop() {
  echo -n $"Stopping $prog"
  echo -e " flanneld ：															  [确定]"
  kill -9 `ps -ef | grep "/usr/bin/flanneld" | awk '{print $2}' | awk 'NR==1'`
  sleep 1
  echo -e "stoped"
}

case "$1" in
  start)
    start
    ;;

  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;

  status)
    ps -ef | grep "/usr/bin/flanneld"
    ;;
  *)
    echo $"Usage: $prog {start|stop|restart|status}" >&2
    exit 1
    ;;
esac

exit 0