apiVersion: v1
kind: ReplicationController
metadata:
  name: monitoring-microblog-v1
  namespace: kingdee-smoke-ab
  labels:
    k8s-app: microblog-ab
    version: v1
spec:
  replicas: 1
  selector:
    k8s-app: microblog-ab
    version: v1
  template:
    metadata:
      labels:
        k8s-app: microblog-ab
        version: v1
    spec:
      containers:
        - image: 172.20.10.220:5000/kingdee/microblog-smoke:2015-09-08-18-09-48
          name: microblog-ab