apiVersion: v1
kind: Service
metadata:
  name: microblog-smoke
  namespace: kingdee-smoke
  labels: 
    kingdee/microblog-smoke: "true"
    kingdee/name: "microblog-smoke"
spec: 
  ports: 
    - port: 80
      targetPort: 10091
  selector: 
    k8s-app: microblog

