apiVersion: v1
kind: Service
metadata:
  name: public-smoke
  namespace: kingdee-smoke
  labels: 
    kingdee/public-smoke: "true"
    kingdee/name: "public-smoke"
spec: 
  ports: 
    - port: 80
      targetPort: 10091
  selector: 
    k8s-app: public

