apiVersion: v1
kind: Service
metadata:
  name: res-smoke
  namespace: kingdee-smoke
  labels: 
    kingdee/res-smoke: "true"
    kingdee/name: "res-smoke"
spec: 
  ports: 
    - port: 80
      targetPort: 10091
  selector: 
    k8s-app: res

