apiVersion: v1
kind: ReplicationController
metadata:
  name: monitoring-res-v1
  namespace: kingdee-smoke
  labels:
    k8s-app: res
    version: v1
spec:
  replicas: 1
  selector:
    k8s-app: res
    version: v1
  template:
    metadata:
      labels:
        k8s-app: res
        version: v1
    spec:
      containers:
        - image: 172.20.10.220:5000/kingdee/res-smoke
          name: res