apiVersion: v1
kind: Service
metadata:
  name: space-smoke
  namespace: kingdee-smoke
  labels: 
    kingdee/space-smoke: "true"
    kingdee/name: "space-smoke"
spec: 
  ports: 
    - port: 80
      targetPort: 10091
  selector: 
    k8s-app: space

