apiVersion: v1
kind: Pod
metadata:
  name: cadvisor
  namespace: kube-system
spec:
  containers:
  - name: cadvisor
    image: google/cadvisor:latest
    ports:
      - name: http
        containerPort: 8080
        hostPort: 4194
    volumeMounts:
    - name: varrun
      mountPath: /var/run
      readOnly: false
    - name: cgroup
      mountPath: /sys/fs/cgroup
      readOnly: true
    - name: docker
      mountPath: /var/lib/docker
      readOnly: true
  volumes:
  - name: varrun
    hostPath:
      path: /var/log
  - name: cgroup
    hostPath:
      path: /sys/fs/cgroup/
  - name: docker
    hostPath:
      path: /var/lib/docker/

