apiVersion: v1
kind: Pod
metadata:
  name: cadvisor
  namespace: kube-system
spec:
  containers:
  - name: cadvisor
    image: google/cadvisor:0.16.0
    ports:
      - name: http
        containerPort: 8080
        hostPort: 4194
    volumeMounts:
    - name: rootfs
      mountPath: /rootfs
      readOnly: true
    - name: varrun
      mountPath: /var/run
      readOnly: false
    - name: sys
      mountPath: /sys
      readOnly: true
    - name: docker
      mountPath: /var/lib/docker
      readOnly: true
  volumes:
  - name: rootfs
    hostPath:
      path: /
  - name: varrun
    hostPath:
      path: /var/log
  - name: sys
    hostPath:
      path: /sys
  - name: docker
    hostPath:
      path: /var/lib/docker/

