apiVersion: v1
kind: Pod
metadata:
  name: quagga
  namespace: kube-system
spec:
  containers:
  - name: quagga
    image: index.alauda.cn/georce/router
    securityContext:
        privileged: true
  hostNetwork: true
