[template]
src = "location.tmpl"
## nginx conf.d
dest = "/usr/local/nginx/conf/conf.d/location/master/master.locations.conf"
mode = "0644"
keys = [
  "/registry/services/endpoints/kingdee-master",
]
check_cmd = "/usr/sbin/nginx -t -c {{.src}}"
reload_cmd = "/usr/sbin/service nginx restart"
