apiVersion: v1
kind: Service
metadata:
  name: microblog-master
  namespace: kingdee-master
  labels: 
    kingdee/microblog-master: "true"
    kingdee/name: "microblog-master"
spec: 
  ports: 
    - port: 80
      targetPort: 10091
  selector: 
    k8s-app: microblog

