apiVersion: v1
kind: ReplicationController
metadata:
  name: monitoring-microblog-v1
  namespace: kingdee-master
  labels:
    k8s-app: microblog
    version: v1
spec:
  replicas: 2
  selector:
    k8s-app: microblog
    version: v1
  template:
    metadata:
      labels:
        k8s-app: microblog
        version: v1
    spec:
      containers:
        - image: kingdee/microblog-master
          name: microblog