apiVersion: v1
kind: ReplicationController
metadata:
  name: monitoring-public-v1
  namespace: kingdee-master
  labels:
    k8s-app: public
    version: v1
spec:
  replicas: 2
  selector:
    k8s-app: public
    version: v1
  template:
    metadata:
      labels:
        k8s-app: public
        version: v1
    spec:
      containers:
        - image: kingdee/public-master
          name: public