apiVersion: v1
kind: Service
metadata:
  name: public-master
  namespace: kingdee-master
  labels: 
    kingdee/public-master: "true"
    kingdee/name: "public-master"
spec: 
  ports: 
    - port: 80
      targetPort: 10091
  selector: 
    k8s-app: public

