apiVersion: v1
kind: Service
metadata:
  name: res-master
  namespace: kingdee-master
  labels: 
    kingdee/res-master: "true"
    kingdee/name: "res-master"
spec: 
  ports: 
    - port: 80
      targetPort: 10091
  selector: 
    k8s-app: res

