apiVersion: v1
kind: Service
metadata:
  name: space-master
  namespace: kingdee-master
  labels: 
    kingdee/space-master: "true"
    kingdee/name: "space-master"
spec: 
  ports: 
    - port: 80
      targetPort: 10091
  selector: 
    k8s-app: space

