apiVersion: v1
kind: ReplicationController
metadata:
  name: monitoring-space-v1
  namespace: kingdee-master
  labels:
    k8s-app: space
    version: v1
spec:
  replicas: 2
  selector:
    k8s-app: space
    version: v1
  template:
    metadata:
      labels:
        k8s-app: space
        version: v1
    spec:
      containers:
        - image: kingdee/space-master
          name: space