apiVersion: v1
kind: ReplicationController
metadata:
  name: monitoring-heapster-v5
  namespace: kube-system
  labels:
    k8s-app: heapster
    version: v5
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: heapster
    version: v5
  template:
    metadata:
      labels:
        k8s-app: heapster
        version: v5
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
        - image: kubernetes/heapster:v0.17.0
          name: heapster
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
          command:
            - /heapster
            - --source=cadvisor:external?cadvisorPort=4194&hostsFile=/var/run/heapster/hosts/hosts.json
            - --sink=influxdb:http://192.168.1.237:8086
          volumeMounts:
          - name: hosts
            mountPath: /var/run/heapster/hosts
            readOnly: true
      volumes:
      - name: hosts
        hostPath:
          path: /etc/heapster.d/
