apiVersion: v1
kind: Pod
metadata:
  name: packetbeat
  namespace: kube-system
spec:
  containers:
  - name: packetbeat
    image: packetbeat
    command:
            - packetbeat
            - -e 
            - -c /etc/packetbeat/packetbeat.yml
    securityContext:
    volumeMounts:
      - name: packetbeat-logs
        mountPath: /var/log/packetbeat
  volumes:
  - name:  packetbeat-logs
    hostPath:
      path: /var/log
  hostNetwork: true