apiVersion: v1
kind: ReplicationController
metadata:
  name: monitoring-heapster-v5
  namespace: kube-system
  labels:
    k8s-app: heapster
    version: v5
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: heapster
    version: v5
  template:
    metadata:
      labels:
        k8s-app: heapster
        version: v5
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
        - image: kubernetes/heapster:v0.16.0
          name: heapster
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
          command:
            - /heapster
            - --source=cadvisor:external?cadvisorPort=4194&hostsFile=/var/run/heapster/hosts/hostfile
            - --sink=influxdb:http://monitoring-influxdb:8086
