apiVersion: "v1"
kind: "Pod"
metadata: 
  name: "kube-scheduler"
spec: 
  hostNetwork: true
  containers: 
    - 
      name: "kube-scheduler"
      image: "gcr.io/google_containers/hyperkube:v1.0.3"
      command: 
        - "/bin/sh"
        - "-c"
        - "/hyperkube scheduler --logtostderr=false --v=2 --address=0.0.0.0 --master=172.20.10.221:8080 1>>/var/log/kube-scheduler.log 2>&1"
      livenessProbe: 
        httpGet: 
          path: "/healthz"
          port: 10251
        initialDelaySeconds: 15
        timeoutSeconds: 1
      volumeMounts: 
        - 
          name: "logfile"
          mountPath: "/var/log/kube-scheduler.log"
          readOnly: false
  volumes: 
    - 
      name: "logfile"
      hostPath: 
        path: "/var/log/kube-scheduler.log"
