apiVersion: "v1"
kind: "Pod"
metadata: 
  name: "kube-apiserver"
spec: 
  hostNetwork: true
  containers: 
    - 
      name: "kube-apiserver"
      image: "gcr.io/google_containers/hyperkube:v1.0.3"
      command: 
        - "/bin/sh"
        - "-c"
        - "/hyperkube apiserver --v=2 --logtostderr=false  --etcd-servers=http://192.168.1.237:2379,http://192.168.1.238:2379,http://192.168.1.239:2379 --insecure-bind-address=0.0.0.0 --insecure-port=8080 --allow-privileged=false --secure-port=443 --service-cluster-ip-range=10.100.0.0/16 1>>/var/log/kube-apiserver.log 2>&1"
      volumeMounts: 
        - 
          name: "logfile"
          mountPath: "/var/log/kube-apiserver.log"
          readOnly: false
  volumes: 
    - 
      name: "logfile"
      hostPath: 
        path: "/var/log/kube-apiserver.log"
        